"""Apply corrections maps to raw transcripts and write clean versions."""

import json
import os

RAW_DIR = "data/transcripts/raw"
CLEAN_DIR = "data/transcripts/clean"
os.makedirs(CLEAN_DIR, exist_ok=True)

MIN_KEY_LEN = 5

corrections_by_file = {
    "UC_clPgZzNNheN1-wK0Ngbow_0KjdUZnMwwA": {
        "Tino Fu Malawi": "Tino Fa'asuamaleaui",
        "Angus Cryon": "Angus Crichton",
        "Angus Kiton": "Angus Crichton",
        "Angus Kryton": "Angus Crichton",
        "Hamali Olawatu": "Haumole Olakau'atu",
        "Holly Olawatu": "Haumole Olakau'atu",
        "Olawatu": "Olakau'atu",
        "Lea Halisma": "Leka Halasima",
        "Halisma": "Halasima",
        "Sha Lane": "Shaun Lane",
        "Jermaine Jolof": "Jaimin Jolliffe",
        "Foggetty": "Fogarty",
        "Fogerty": "Fogarty",
        "Jaden Sewa": "Jaydn Su'A",
        "Pat Carrian": "Pat Carrigan",
        "Kieran Floren": "Kieran Foran",
        "Kieran Foreign": "Kieran Foran",
        "Kieran Foren": "Kieran Foran",
        "Dave Fida": "David Fifita",
        "Talis Duncan": "Tallis Duncan",
        "Villami Kick": "Viliame Kikau",
        "Kickau": "Kikau",
        "Maron Clark": "Erin Clark",
        "Aaron Clark": "Erin Clark",
        "Dill Brown": "Dylan Brown",
        "Pane Hass": "Payne Haas",
        "Shane Flanigan": "Shane Flanagan",
        "Karazzi": "Kiraz",
        "Manley": "Manly",
        "the rooers": "the Roosters",
        "Penri": "Penrith",
        "Genanon coming": "Gannon coming",
    },
    "UC5VEgd54Vr7J__gyQhCVd6Q_gkqXsokyWzc": {
        "Reed Mani": "Reed Mahoney",
        "Kalin Ponga": "Kalyn Ponga",
        "Kalin Pong": "Kalyn Ponga",
        "Fletcher Sharp": "Fletcher Sharpe",
        "Herby Farmorth": "Herbie Farnworth",
        "Lassardi": "Lisati",
        "Shawn BL": "Shawn Blore",
        "Jermaine Hopg good": "J'maine Hopgood",
        "Jermaine Hopkins": "J'maine Hopgood",
        "Jermaine Hopgood": "J'maine Hopgood",
        "Jermaine Hopkood": "J'maine Hopgood",
        "HopG good": "J'maine Hopgood",
        "HopG Good": "J'maine Hopgood",
        "Paramata": "Parramatta",
        "Tain Tiki": "Taine Tuaupiki",
        "Clockstead": "Charnze Nicoll-Klokstad",
        "Ali Leah Tower": "Ali Leiataua",
        "Alita tower": "Ali Leiataua",
        "Jacob Labam": "Jacob Laban",
        "Leah Helisma": "Leka Halasima",
        "Lea Halisimo": "Leka Halasima",
        "Kirk Capewell": "Kurt Capewell",
        "Daily Cherry Evans": "Daly Cherry-Evans",
        "Reesei Robson": "Reece Robson",
        "Reese Robson": "Reece Robson",
        "Banana Lu": "Benaiah Ioelu",
        "Bia Lolu": "Benaiah Ioelu",
        "Blake Steve": "Blake Steep",
        "Naf White": "Naufahu Whyte",
        "Nap Butcher": "Nat Butcher",
        "Victor Bradley": "Victor Radley",
        "Angus Kryen": "Angus Crichton",
        "Angus Cryon": "Angus Crichton",
        "Reissi Walsh": "Reece Walsh",
        "Reysi Walsh": "Reece Walsh",
        "Reese Walsh": "Reece Walsh",
        "Isaac Targetgo": "Izack Tago",
        "Isaac Tongo": "Izack Tago",
        "Isaac Tango": "Izack Tago",
        "Nathan Clearary": "Nathan Cleary",
        "Selvin Cobo": "Selwyn Cobbo",
        "Keanu Keiny": "Keano Kini",
        "Femani": "Sialetili Faeamani",
        "Feymani": "Sialetili Faeamani",
        "Mara How": "Arama Hau",
        "Cooper Bay": "Cooper Bai",
        "Josh Patton": "Joshua Patston",
        "Nikico Hines": "Nicholas Hynes",
        "Braden Trindle": "Braydon Trindall",
        "Jesse Colehoon": "Jesse Colquhoun",
        "Jesse Ramian": "Jesse Ramien",
        "Manley": "Manly",
        "Penri": "Penrith",
    },
    "UC5WGzA6l4VztUuW_Q477WuQ_ZRmDnMXNJMQ": {
        "Kalin Pong": "Kalyn Ponga",
        "Kalin Ponga": "Kalyn Ponga",
        "Fletcher Sharp": "Fletcher Sharpe",
        "Brain Burns": "Braidon Burns",
        "Pezant": "Pezet",
        "Jonah Pez": "Jonah Pezet",
        "Catchman": "Couchman",
        "Ratchman": "Couchman",
        "Cooper Bar": "Cooper Bai",
        "Cooper Bay": "Cooper Bai",
        "Cooper buy": "Cooper Bai",
        "Cole Hoon": "Jesse Colquhoun",
        "Jesse Coh": "Jesse Colquhoun",
        "Tanny Ella Pekka": "Taniela Paseka",
        "Thomas Flagler": "Thomas Flegler",
        "Orin Keley": "Oryn Keeley",
        "Sebastian Sea": "Sebastian Su'a",
        "Max Platt": "Max Plath",
        "Daniel Sudi": "Daniel Saifiti",
        "Adavalu Lassardi": "Ativalu Lisati",
        "Lassardi": "Lisati",
        "Dave Moali": "Davvy Moale",
        "Tui Kamakamea": "Tui Kamikamica",
        "Keon Kalamatangi": "Keaon Koloamatangi",
        "Tino Fasu Malawi": "Tino Fa'asuamaleaui",
        "Talis Duncan": "Tallis Duncan",
        "Josh Pton": "Joshua Patston",
        "Arama How": "Arama Hau",
        "Jaden Campbell": "Jayden Campbell",
        "Jermaine Hopgood": "J'maine Hopgood",
        "Germaine Hopg good": "J'maine Hopgood",
        "Hobgood": "Hopgood",
        "HopGood": "Hopgood",
        "Ben Yellow": "Benaiah Ioelu",
        "Reese Robson": "Reece Robson",
        "Blake Brily": "Blayke Brailey",
        "Hamasi Mcini": "Heamasi Makasini",
        "Maxini": "Makasini",
        "Reese Walsh": "Reece Walsh",
        "James Desco": "James Tedesco",
        "Angus Kryen": "Angus Crichton",
        "Nathan Clearary": "Nathan Cleary",
        "Nikico Hines": "Nicholas Hynes",
        "Adam Dwey": "Adam Doueihi",
        "Sali Fammani": "Sialetili Faeamani",
        "Manley": "Manly",
        "Paramea": "Parramatta",
        "Penri": "Penrith",
        "Sha BL": "Shawn Blore",
    },
    "UCf1s3PC9aOw5MUOcklUWosg_LAqgZITJloo": {
        "Steven Kiteon": "Stephen Crichton",
        "Steven Kiton": "Stephen Crichton",
        "Steven Kryton": "Stephen Crichton",
        "Steven Cryon": "Stephen Crichton",
        "Herby Farmorth": "Herbie Farnworth",
        "Herby Fworth": "Herbie Farnworth",
        "Farmorth": "Farnworth",
        "Payne Har": "Payne Haas",
        "Panhar": "Payne Haas",
        "Colomatangi": "Koloamatangi",
        "Kon Katangi": "Keaon Koloamatangi",
        "Katangi": "Koloamatangi",
        "Jack Heatherington": "Jack Hetherington",
        "Heatherington": "Hetherington",
        "Cam McKinis": "Cameron McInnes",
        "Colhoon": "Colquhoun",
        "Jesse Choon": "Jesse Colquhoun",
        "Dave Fida": "David Fifita",
        "Cooper Bayer": "Cooper Bai",
        "Cooper Bay": "Cooper Bai",
        "Kooper Bay": "Cooper Bai",
        "Koopa buyer": "Cooper Bai",
        "Joe Chen": "Joe Chan",
        "Reese Walsh": "Reece Walsh",
        "Kean Kiny": "Keano Kini",
        "Keano Kiny": "Keano Kini",
        "Kiana Kiny": "Keano Kini",
        "Kale Ero": "Kayal Iro",
        "Kalen Ponga": "Kalyn Ponga",
        "Kale Ponga": "Kalyn Ponga",
        "Jonah Pez": "Jonah Pezet",
        "Tino for Suma AI": "Tino Fa'asuamaleaui",
        "Cam Monster": "Cameron Munster",
        "Cam Monson": "Cameron Munster",
        "Isaiah Papa": "Isaiah Papali'i",
        "Maxini": "Sialetili Faeamani",
        "Feymani": "Sialetili Faeamani",
        "Feyammani": "Sialetili Faeamani",
        "Daniel Atinson": "Daniel Atkinson",
        "Jacob Carz": "Jacob Kiraz",
        "Reed Miny": "Reed Mahoney",
        "Reed Manny": "Reed Mahoney",
        "Reed Money": "Reed Mahoney",
        "Sonny Luke": "Soni Luke",
        "Sony Luke": "Soni Luke",
        "Tom Deon": "Tom Dearden",
        "Sand Smith": "Sandon Smith",
        "David Farlay": "David Fale",
        "Jacob Little": "Jacob Liddle",
        "Jermaine Mchuan": "Jermaine McEwen",
        "Miles Martin": "Myles Martin",
        "Pat Carrian": "Pat Carrigan",
        "Penri": "Penrith",
        "Manley": "Manly",
        "Drink Water": "Drinkwater",
    },
    "UCf1s3PC9aOw5MUOcklUWosg_mRe9hdLvLqU": {
        "Tom Travoyovich": "Tom Trbojevic",
        "Clearary": "Cleary",
        "Ruben Garrick": "Reuben Garrick",
        "Ken Ponga": "Kalyn Ponga",
        "Damen Cook": "Damien Cook",
        "Jermaine Hopwood": "J'maine Hopgood",
        "Germaine Hop good": "J'maine Hopgood",
        "HopGood": "Hopgood",
        "Hop Good": "Hopgood",
        "Jacob Leen": "Jacob Laban",
        "Morgan Smithy": "Morgan Smithies",
        "Matt Tumiko": "Matthew Timoko",
        "Sua Takayaho": "Siua Taukei'aho",
        "Kobe Heatherington": "Kobe Hetherington",
        "Kobe Eington": "Kobe Hetherington",
        "Tanya PCO": "Taniela Paseka",
        "Sanders Smith": "Sandon Smith",
        "Angus Kryton": "Angus Crichton",
        "Angus Kiteon": "Angus Crichton",
        "Angus Cryon": "Angus Crichton",
        "Victor Bradley": "Victor Radley",
        "Jadden Sullivan": "Jayden Sullivan",
        "Jaden Sullivan": "Jayden Sullivan",
        "Shan Keeper": "Sean Keppie",
        "Sha Keepy": "Sean Keppie",
        "Kong Katangi": "Keaon Koloamatangi",
        "Maxini": "Heamasi Makasini",
        "Stafford Toa": "Starford To'a",
        "Talon May": "Taylan May",
        "Kai Pierce Pool": "Kai Pearce-Paul",
        "Kai Pierce Paul": "Kai Pearce-Paul",
        "Shaun Blau": "Shawn Blore",
        "Lassardi": "Lisati",
        "Penri": "Penrith",
        "Isaac Tongo": "Izack Tago",
        "Manley": "Manly",
        "Drink Water": "Drinkwater",
        "Braden Burns": "Braidon Burns",
        "Jacob Little": "Jacob Liddle",
        "Jonah Pez": "Jonah Pezet",
        "Reese Walsh": "Reece Walsh",
        "Nathan Clearary": "Nathan Cleary",
        "Paramata": "Parramatta",
        "Paramea": "Parramatta",
        "Rabbidos": "Rabbitohs",
        "Rob Toy": "Robert Toia",
    },
    "UCMReymNfmodE1OEc9fQvwQQ_QMRJ5yFEmxI": {
        "Reese Walsh": "Reece Walsh",
        "Paramata": "Parramatta",
        "Blake Brily": "Blayke Brailey",
        "Blake Brayley": "Blayke Brailey",
        "Jermaine Hogood": "J'maine Hopgood",
        "Hawkood": "Hopgood",
        "Offgood": "Hopgood",
        "Hop Good": "Hopgood",
        "Hobgood": "Hopgood",
        "Angus Cryon": "Angus Crichton",
        "Hamasi Makasini": "Heamasi Makasini",
        "Maxini": "Makasini",
        "Talon May": "Taylan May",
        "Stafford tile": "Starford To'a",
        "Braden Burns": "Braidon Burns",
        "Jacob little": "Jacob Liddle",
        "Lassardi": "Lisati",
        "Alec McDonald": "Alec MacDonald",
        "Isaac Tango": "Izack Tago",
        "Teague Wilton": "Teig Wilton",
        "Manley": "Manly",
        "Arama how": "Arama Hau",
        "Trindle": "Braydon Trindall",
        "Braden Tindle": "Braydon Trindall",
        "Nathan Clearary": "Nathan Cleary",
        "Jesse Kolhoon": "Jesse Colquhoun",
        "Herby Farmorth": "Herbie Farnworth",
        "Nikico Hines": "Nicholas Hynes",
        "Penri": "Penrith",
        "Rabbidos": "Rabbitohs",
    },
    "UCs5CHx-kIwy2NF9DFesWE8w__I9aX-2UNa8": {
        "Sale Longo": "Sua Fa'alogo",
        "Suf Longo": "Sua Fa'alogo",
        "Nick Meanie": "Nick Meaney",
        "Nick Mey": "Nick Meaney",
        "Nico Hines": "Nicholas Hynes",
        "Nick Hines": "Nicholas Hynes",
        "Nikah Hines": "Nicholas Hynes",
        "Jerome Hughes": "Jahrome Hughes",
        "Stefano Kamano": "Stefano Utoikamanu",
        "Stefani Kamano": "Stefano Utoikamanu",
        "Tokamanu": "Utoikamanu",
        "Lassardi": "Lisati",
        "David Mole": "Davvy Moale",
        "David Mle": "Davvy Moale",
        "Cooper Clark": "Cooper Clarke",
        "Trent Lero": "Trent Loiero",
        "Shan Blau": "Shawn Blore",
        "Shawn Blur": "Shawn Blore",
        "Heatherington": "Hetherington",
        "Isaiah Yongi": "Isaiah Iongi",
        "Will Panaceini": "Will Penisini",
        "Penaceini": "Will Penisini",
        "Will Penini": "Will Penisini",
        "Jonah Pezit": "Jonah Pezet",
        "HopGood": "Hopgood",
        "Hop Good": "Hopgood",
        "HopG Good": "Hopgood",
        "Hopkood": "Hopgood",
        "Jermaine Hobgood": "J'maine Hopgood",
        "Jermaine Hopgood": "J'maine Hopgood",
        "Jermaine Hopkood": "J'maine Hopgood",
        "Kelma Tangi": "Kelma Tuilagi",
        "Debbellan": "de Belin",
        "Jack Deellan": "Jack de Belin",
        "Matt Dury": "Matthew Doorey",
        "Tal Silva": "Tallyn Da Silva",
        "Josh Pston": "Joshua Patston",
        "Paramea": "Parramatta",
        "Paramata": "Parramatta",
        "Ryan Madison": "Ryan Matterson",
        "Reese Walsh": "Reece Walsh",
        "Reese Robson": "Reece Robson",
        "Angus Krydden": "Angus Crichton",
        "Spencer Lenu": "Spencer Leniu",
        "Gus Kiteon": "Angus Crichton",
        "Gus Kiton": "Angus Crichton",
        "Nathan Clearary": "Nathan Cleary",
        "Penri": "Penrith",
        "Manley": "Manly",
    },
    "UCs5CHx-kIwy2NF9DFesWE8w_2OMefy0SMeo": {
        "Reese Walsh": "Reece Walsh",
        "Arma How": "Arama Hau",
        "Josh Patson": "Joshua Patston",
        "Lassardi": "Ativalu Lisati",
        "Maxini": "Heamasi Makasini",
        "Mcassini": "Heamasi Makasini",
        "Ryan Catchman": "Ryan Couchman",
        "Leia Tower": "Ali Leiataua",
        "Jacob Leen": "Jacob Laban",
        "Gus Kiteon": "Angus Crichton",
        "Gus Kitton": "Angus Crichton",
        "Angus Gen": "Angus Crichton",
        "Spencer Lingu": "Spencer Leniu",
        "Spencer Lenu": "Spencer Leniu",
        "Natt Butcher": "Nat Butcher",
        "Kon Katangi": "Keaon Koloamatangi",
        "Rob Toyery": "Robert Toia",
        "Rob Toyer": "Robert Toia",
        "Daily Trey Evans": "Daly Cherry-Evans",
        "Deli Cherry Evans": "Daly Cherry-Evans",
        "Nfahu White": "Naufahu Whyte",
        "Paramea": "Parramatta",
        "Penri": "Penrith",
        "Rabboss": "Rabbitohs",
        "rabbidos": "Rabbitohs",
        "Halisimma": "Leka Halasima",
        "Braden Burns": "Braidon Burns",
        "Adam Dwey": "Adam Doueihi",
        "David Fida": "David Fifita",
        "David Federer": "David Fifita",
        "Jaden Sullivan": "Jayden Sullivan",
        "Nathan Clearary": "Nathan Cleary",
        "Manley": "Manly",
        "Macini": "Heamasi Makasini",
    },
    "UCs5CHx-kIwy2NF9DFesWE8w_8Kc3P1BQEUE": {
        "Nathan Clearary": "Nathan Cleary",
        "Ko Wix": "Kaeo Weekes",
        "Dane Lori": "Daine Laurie",
        "Matt Tomokco": "Matthew Timoko",
        "Si Sagi": "Simi Sasagi",
        "Laker Halisma": "Leka Halasima",
        "Halisma": "Halasima",
        "Halisima": "Halasima",
        "Helisma": "Halasima",
        "Isaiah Yongi": "Isaiah Iongi",
        "Reese Robson": "Reece Robson",
        "Bronson Zer": "Bronson Xerri",
        "LeBron Zer": "Bronson Xerri",
        "Jacob Carz": "Jacob Kiraz",
        "Locky Galvin": "Lachlan Galvin",
        "Shauna Salvin": "Sean O'Sullivan",
        "Brennan Pierur": "Brendan Piakura",
        "Herby Farmorth": "Herbie Farnworth",
        "Angus Kryen": "Angus Crichton",
        "Angus Cryen": "Angus Crichton",
        "Gus Kiteon": "Angus Crichton",
        "Angus Curtin": "Angus Crichton",
        "David Fida": "David Fifita",
        "Nefu White": "Naufahu Whyte",
        "Mafu White": "Naufahu Whyte",
        "Rob Toyera": "Robert Toia",
        "Su Wong": "Siua Wong",
        "Paramea": "Parramatta",
        "Paramata": "Parramatta",
        "Penri Panthers": "Penrith Panthers",
        "Freddy Lassi": "Freddy Lussick",
        "Failongo": "Sua Fa'alogo",
        "Fail Longo": "Sua Fa'alogo",
        "Lassardi": "Lisati",
        "Shawn Blur": "Shawn Blore",
        "Shawn Blau": "Shawn Blore",
        "Shawn BL": "Shawn Blore",
        "Jonah Pez": "Jonah Pezet",
        "Reed Mani": "Reed Mahoney",
        "Reed Manny": "Reed Mahoney",
        "Adam Dewey": "Adam Doueihi",
        "Reese Walsh": "Reece Walsh",
        "Ree Walsh": "Reece Walsh",
        "Fletcher Sharp": "Fletcher Sharpe",
        "Sand and Smith": "Sandon Smith",
        "Jermaine Mchuan": "Jermaine McEwen",
        "Gus Kaiden": "Angus Crichton",
        "Kale Pong": "Kalyn Ponga",
        "Kaylin Ponger": "Kalyn Ponga",
        "halen Ponga": "Kalyn Ponga",
        "Blake Brily": "Blayke Brailey",
        "Manley": "Manly",
    },
    "UCs5CHx-kIwy2NF9DFesWE8w_pZVYbo5-RCo": {
        "Reese Walsh": "Reece Walsh",
        "Jacob Carz": "Jacob Kiraz",
        "Selwin Cobo": "Selwyn Cobbo",
        "Herby Farmorth": "Herbie Farnworth",
        "Nick Meanie": "Nick Meaney",
        "Kiana Keany": "Keano Kini",
        "Greg Mazu": "Greg Marzhew",
        "Paul Alamotti": "Paul Alamoti",
        "Failongo": "Fa'alogo",
        "Sale Longo": "Sua Fa'alogo",
        "Talis Duncan": "Tallis Duncan",
        "Talon May": "Taylan May",
        "Braden Best": "Bradman Best",
        "Braden Burns": "Braidon Burns",
        "Casey Mlan": "Casey McLean",
        "Steven Kiteon": "Stephen Crichton",
        "Clearary": "Cleary",
        "Cherry Evans": "Cherry-Evans",
        "Rob Toyer": "Robert Toia",
        "Penacini": "Penisini",
        "Panaceini": "Penisini",
        "Fletcher Sharp": "Fletcher Sharpe",
        "Jaden Campbell": "Jayden Campbell",
        "Manley": "Manly",
        "Penri": "Penrith",
        "Paramea": "Parramatta",
    },
}

for filename_stem, corrections in corrections_by_file.items():
    raw_path = f"{RAW_DIR}/{filename_stem}.json"
    clean_path = f"{CLEAN_DIR}/{filename_stem}.json"

    with open(raw_path, encoding="utf-8") as f:
        data = json.load(f)

    safe = {k: v for k, v in corrections.items() if len(k) >= MIN_KEY_LEN and k != v}
    sorted_corrections = sorted(safe.items(), key=lambda x: -len(x[0]))

    counts = {}
    for seg in data["segments"]:
        text = seg["text"]
        for old, new in sorted_corrections:
            if old in text:
                text = text.replace(old, new)
                counts[f"{old} -> {new}"] = counts.get(f"{old} -> {new}", 0) + 1
        seg["text"] = text

    with open(clean_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    total_fixes = sum(counts.values())
    print(f"{filename_stem}: {len(data['segments'])} segs, {len(safe)} safe corrections, {total_fixes} replacements")

print("\nDone. All 10 clean files written.")
